/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jadyn_mediakit_gl_GLJni */

#ifndef _Included_com_jadyn_mediakit_gl_GLJni
#define _Included_com_jadyn_mediakit_gl_GLJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jadyn_mediakit_gl_GLJni
 * Method:    glReadPixels
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_com_jadyn_mediakit_gl_GLJni_glReadPixels
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
