/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jadyn_mediakit_player_ALVideoController */

#ifndef _Included_com_jadyn_mediakit_player_ALVideoController
#define _Included_com_jadyn_mediakit_player_ALVideoController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jadyn_mediakit_player_ALVideoController
 * Method:    prepare
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jadyn_mediakit_player_ALVideoController_prepare
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jadyn_mediakit_player_ALVideoController
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jadyn_mediakit_player_ALVideoController_start
  (JNIEnv *, jobject);

/*
 * Class:     com_jadyn_mediakit_player_ALVideoController
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jadyn_mediakit_player_ALVideoController_stop
  (JNIEnv *, jobject);

/*
 * Class:     com_jadyn_mediakit_player_ALVideoController
 * Method:    pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jadyn_mediakit_player_ALVideoController_pause
  (JNIEnv *, jobject);

/*
 * Class:     com_jadyn_mediakit_player_ALVideoController
 * Method:    seekTo
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_jadyn_mediakit_player_ALVideoController_seekTo
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_jadyn_mediakit_player_ALVideoController
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jadyn_mediakit_player_ALVideoController_release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
